### ISSUE TITLE
cannot load such file -- sqlite3/sqlite3_native (LoadError)

### ISSUE THREAD

**Issue by anilreddy** [sparklemotion/sqlite3-ruby#137]
Hi,

Today i have updated ruby ver. to 2.1.3 in windows 8 OS and tried to start rails server and I came up with this issue.

``` batchFile
D:\Web Developement\Ruby on Rails\simple_cms>rails s
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.9-x86-mingw32/lib/sqlite3.rb:6:in
 `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.9-x86-mingw32/lib/sq
lite3.rb:6:in `rescue in <top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.9-x86-mingw32/lib/sq
lite3.rb:2:in `<top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/runtim
e.rb:76:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/runtim
e.rb:76:in `block (2 levels) in require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/runtim
e.rb:72:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/runtim
e.rb:72:in `block in require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/runtim
e.rb:61:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/runtim
e.rb:61:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler.rb:133
:in `require'
        from D:/Web Developement/Ruby on Rails/simple_cms/config/application.rb:
7:in `<top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/command
s/commands_tasks.rb:79:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/command
s/commands_tasks.rb:79:in `block in server'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/command
s/commands_tasks.rb:76:in `tap'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/command
s/commands_tasks.rb:76:in `server'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/command
s/commands_tasks.rb:40:in `run_command!'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/command
s.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by Ajedi32** [comment]
Note to future readers: If you're getting a similar error to this with sqlite3-ruby v1.3.11. #185 is likely the issue you're experiencing.
