### ISSUE TITLE
Should the driver handle malformed MATCH expressions?

### ISSUE THREAD

**Issue by dkam** [sparklemotion/sqlite3-ruby#192]
I'm not sure this is supposed to be handled by the programmer, or the driver.  Performing a MATCH query containing a bracket  (  causes an exception. 

Is this a bug or should I be escaping values used in a query?   It occurs with **#execute** and with prepared statements. 

```ruby
require 'sqlite3'

db = SQLite3::Database.new "/tmp/database.db"

db.execute("DROP table if exists example")
db.execute("CREATE VIRTUAL TABLE example USING fts4(text)")
db.execute("INSERT INTO example (text)  VALUES (?)", "Testo Goodo")


query = "Test*"
=> "Test*"
irb(main):021:0> db.execute("select * from example where example match ?", query)
=> [["Testo Goodo"]]

irb(main):022:0> query = "Te(st"
=> "Te(st"
irb(main):023:0> db.execute("select * from example where example match ?", query)
SQLite3::SQLException: malformed MATCH expression: [Te(st]
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `step'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `block in each'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `loop'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `each'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `to_a'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `block in execute'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:95:in `prepare'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
	from (irb):23
	from /Users/dkam/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):024:0> 
irb(main):025:0* stm = db.prepare("select * from example where example match ?")
=> #<SQLite3::Statement:0x007fdc13a7b7e0 @connection=#<SQLite3::Database:0x007fdc13a83f58 @tracefunc=nil, @authorizer=nil, @encoding=#<Encoding:UTF-8>, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=nil, @type_translation=nil, @readonly=false>, @remainder="", @columns=nil, @types=nil>
irb(main):026:0> stm.execute("test")
=> #<SQLite3::ResultSet:0x007fdc13a73e28 @db=#<SQLite3::Database:0x007fdc13a83f58 @tracefunc=nil, @authorizer=nil, @encoding=#<Encoding:UTF-8>, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=nil, @type_translation=nil, @readonly=false>, @stmt=#<SQLite3::Statement:0x007fdc13a7b7e0 @connection=#<SQLite3::Database:0x007fdc13a83f58 @tracefunc=nil, @authorizer=nil, @encoding=#<Encoding:UTF-8>, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=nil, @type_translation=nil, @readonly=false>, @remainder="", @columns=nil, @types=nil, @results=#<SQLite3::ResultSet:0x007fdc13a73e28 ...>>>
irb(main):027:0> stm.execute("test").to_a
=> []
irb(main):028:0> stm.execute("test*").to_a
=> [["Testo Goodo"]]
irb(main):029:0> stm.execute("te(st*").to_a
SQLite3::SQLException: malformed MATCH expression: [te(st*]
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/resultset.rb:108:in `step'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/resultset.rb:108:in `next'
	from /Users/dkam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/resultset.rb:137:in `each'
	from (irb):29:in `to_a'
	from (irb):29
	from /Users/dkam/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):030:0> stm.execute("te(st*").to_a
```

**Comment by tenderlove** [comment]
I think this is up to the developer to escape.  According to [the docs](https://www.sqlite.org/lang_expr.html):

> The MATCH operator is a special syntax for the match() application-defined function. The default match() function implementation raises an exception and is not really useful for anything. But extensions can override the match() function with more helpful logic.

Since we can't know how `match` function is implemented, we can't know how to escape anything.  The developer must be the one that installed the `match` function, so only the person actually using the library knows the correct way to escape for the function they installed.

Hopefully that makes sense!

**Comment by dkam** [comment]
Perfectly reasonable.  Thanks.
