### ISSUE TITLE
What sqllite engine version is supported?

### ISSUE THREAD

**Issue by Ronserruya** [sparklemotion/sqlite3-ruby#269]
I tried to use this statement 

"INSERT INTO words values (?, ?) 
         on conflict(word) do update set
         instances = instances + ?"

This works fine on sqlite 2.29, and should work since 2.24. However I get this error

/var/lib/gems/2.3.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `initialize': near "on": syntax error (SQLite3::SQLException)

Is this not supported?

**Comment by krists** [comment]
Hi, @Ronserruya 
By default sqlite3 compiles with 3.22.0 
```
 irb -rsqlite3
>> SQLite3::SQLITE_VERSION
=> "3.22.0"
>> SQLite3::VERSION
=> "1.4.1"
```
To get newer version you need to pass additional include parameters when compiling native extension

**Comment by Ronserruya** [comment]
Thanks, but I still get the error

```
irb(main):001:0> SQLite3::SQLITE_VERSION
=> "3.29.0"
irb(main):002:0> db = SQLite3::Database.new "test.db"
=> #<SQLite3::Database:0x000000025cb000 @tracefunc=nil, @authorizer=nil, @encoding=nil, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=nil, @type_translation=nil, @type_translator=#<Proc:0x000000025eb3a0@/var/lib/gems/2.3.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:722 (lambda)>, @readonly=false>
irb(main):003:0> db.execute("insert into words values ('ron', 2) on conflict(word) do update set instances = instances + 1")
SQLite3::SQLException: near "on": syntax error
	from /var/lib/gems/2.3.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `initialize'
	from /var/lib/gems/2.3.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `new'
	from /var/lib/gems/2.3.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `prepare'
	from /var/lib/gems/2.3.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:193:in `execute'
	from (irb):3
	from /usr/bin/irb:11:in `<main>'
irb(main):004:0>
```

**Comment by sterankin** [comment]
Apologies to hijack - but I have a similar issue.
I have rspec tests which pass locally, but they fail on the CI build.  Since we are using the same ruby version and the same sqlite3 gem version, I was at a loss as to what the issue could be.

I noticed when adding the following code to my tests:

```
sql_version= ActiveRecord::Base.connection.execute("select sqlite_version();")
      puts "SQL version is " + sql_version.first.to_s
```

The sql version on my local machine was: `{"sqlite_version()"=>"3.29.0", 0=>"3.29.0"}`

But on the CI server the same code reveals:  `{"sqlite_version()"=>"3.7.17", 0=>"3.7.17"}`

Could this be the cause if my failing specs?

`SQLite3::SQLException: near "WITH": syntax error: ;WITH included_items as (`

My next step is to try an replicate this locally, but how can I force the sqlite3 gem to use an older version of sqlite3?
