### ISSUE TITLE
cannot load such file -- sqlite3/sqlite3_native (LoadError)

### ISSUE THREAD

**Issue by yzidzaini** [sparklemotion/sqlite3-ruby#291]
C:\Users\yazid\Documents\demo rails>rails server
Traceback (most recent call last):
        21: from bin/rails:9:in `<main>'
        20: from bin/rails:9:in `require'
        19: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
        18: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
        17: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
        16: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        15: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        14: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        13: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
        12: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
        11: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
        10: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
         9: from C:/Users/yazid/Documents/demo rails/config/application.rb:7:in `<top (required)>'
         8: from G:/Ruby/lib/ruby/2.6.0/bundler.rb:114:in `require'
         7: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
         6: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
         5: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
         4: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
         3: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
         2: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
         1: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:4:in `<top (required)>'
G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:4:in `require': cannot load such file -- sqlite3/2.6/sqlite3_native (LoadError)
        22: from bin/rails:9:in `<main>'
        21: from bin/rails:9:in `require'
        20: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
        19: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
        18: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
        17: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        16: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        15: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        14: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
        13: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
        12: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
        11: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
        10: from C:/Users/yazid/Documents/demo rails/config/application.rb:7:in `<top (required)>'
         9: from G:/Ruby/lib/ruby/2.6.0/bundler.rb:114:in `require'
         8: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
         7: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
         6: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
         5: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
         4: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
         3: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
         2: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
         1: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:6:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)

**Comment by edward-ellis** [comment]
You are trying to use sqlite3 with Windows and Ruby 2.6.  Sqlite3 version 1.3.13 contains a native DLL for Ruby 2.0 through 2.4 when installed on Ruby 2.6.  It does not contain a native DLL for Ruby 2.6.

**Comment by JackLovel** [comment]
> C:\Users\yazid\Documents\demo rails>rails server
> Traceback (most recent call last):
> 21: from bin/rails:9:in `<main>' 20: from bin/rails:9:in `require'
> 19: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>' 18: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
> 17: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform' 16: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
> 15: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command' 14: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
> 13: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform' 12: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
> 11: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform' 10: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
> 9: from C:/Users/yazid/Documents/demo rails/config/application.rb:7:in `<top (required)>' 8: from G:/Ruby/lib/ruby/2.6.0/bundler.rb:114:in `require'
> 7: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require' 6: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
> 5: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require' 4: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
> 3: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require' 2: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
> 1: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:4:in `<top (required)>' G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:4:in `require': cannot load such file -- sqlite3/2.6/sqlite3_native (LoadError)
> 22: from bin/rails:9:in `<main>' 21: from bin/rails:9:in `require'
> 20: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>' 19: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
> 18: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform' 17: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
> 16: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command' 15: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
> 14: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform' 13: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
> 12: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform' 11: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
> 10: from C:/Users/yazid/Documents/demo rails/config/application.rb:7:in `<top (required)>' 9: from G:/Ruby/lib/ruby/2.6.0/bundler.rb:114:in `require'
> 8: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require' 7: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
> 6: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require' 5: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
> 4: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require' 3: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
> 2: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:2:in `<top (required)>' 1: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
> G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:6:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)

You can try use `gem "sqlite3"`  in Gemfile file without  sqlite3 version; 
then run it 
```
bundle install 
```

**Comment by JackLovel** [comment]
> > C:\Users\yazid\Documents\demo rails>rails server
> > Traceback (most recent call last):
> > 21: from bin/rails:9:in `<main>' 20: from bin/rails:9:in `require'
> > 19: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>' 18: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
> > 17: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform' 16: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
> > 15: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command' 14: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
> > 13: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform' 12: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
> > 11: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform' 10: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
> > 9: from C:/Users/yazid/Documents/demo rails/config/application.rb:7:in `<top (required)>' 8: from G:/Ruby/lib/ruby/2.6.0/bundler.rb:114:in `require'
> > 7: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require' 6: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
> > 5: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require' 4: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
> > 3: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require' 2: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
> > 1: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:4:in `<top (required)>' G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:4:in `require': cannot load such file -- sqlite3/2.6/sqlite3_native (LoadError)
> > 22: from bin/rails:9:in `<main>' 21: from bin/rails:9:in `require'
> > 20: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>' 19: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
> > 18: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform' 17: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
> > 16: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command' 15: from G:/Ruby/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
> > 14: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform' 13: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
> > 12: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform' 11: from G:/Ruby/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
> > 10: from C:/Users/yazid/Documents/demo rails/config/application.rb:7:in `<top (required)>' 9: from G:/Ruby/lib/ruby/2.6.0/bundler.rb:114:in `require'
> > 8: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require' 7: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
> > 6: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require' 5: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
> > 4: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require' 3: from G:/Ruby/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
> > 2: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:2:in `<top (required)>' 1: from G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
> > G:/Ruby/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13-x64-mingw32/lib/sqlite3.rb:6:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
> 
> You can try use `gem "sqlite3"` in Gemfile file without sqlite3 version;
> then run it
> 
> ```
> bundle install 
> ```

My environment:
```
system: window10 
ruby: ruby 3.0.0-p0
rails: 6.1.3
```
