### ISSUE TITLE
sqlite3-ruby won't build on M1 mac

### ISSUE THREAD

**Issue by jaywritescode** [sparklemotion/sqlite3-ruby#313]
While I've seen a lot of questions about getting the compilation and linking process working on arm64 macs, I haven't seen any with the full failing output yet, or any with suggestions for moving forward. Hopefully I can at least help with the first part of that. This is on a Mac running the M1 core.

First, the arm64 version of sqlite3 is installed via homebrew:
```
❯ lipo -info /opt/homebrew/opt/sqlite/bin/sqlite3
Non-fat file: /opt/homebrew/opt/sqlite/bin/sqlite3 is architecture: arm64
```

```
❯ bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
[...gems installed successfully omitted...]
Installing sqlite3 1.4.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.2/ext/sqlite3
/Users/jay/.frum/versions/3.1.0/bin/ruby -I /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0 -r ./siteconf20220218-16845-a4oq1m.rb
extconf.rb --with-sqlite3-dir\=/opt/homebrew/opt/sqlite
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... yes
checking for -ldl... yes
checking for sqlite3_libversion_number() in -lsqlite3... no
sqlite3 is missing. Try 'brew install sqlite3',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jay/.frum/versions/3.1.0/bin/$(RUBY_BASE_NAME)
	--with-sqlcipher
	--without-sqlcipher
	--with-sqlcipher
	--without-sqlcipher
	--with-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/lib
	--with-sqlite3-config
	--without-sqlite3-config
	--with-pkg-config
	--without-pkg-config
	--with-sqlcipher
	--without-sqlcipher
	--with-pthread-dir
	--without-pthread-dir
	--with-pthread-include
	--without-pthread-include=${pthread-dir}/include
	--with-pthread-lib
	--without-pthread-lib=${pthread-dir}/lib
	--with-pthreadlib
	--without-pthreadlib
	--with-dl-dir
	--without-dl-dir
	--with-dl-include
	--without-dl-include=${dl-dir}/include
	--with-dl-lib
	--without-dl-lib=${dl-dir}/lib
	--with-dllib
	--without-dllib
	--with-sqlcipher
	--without-sqlcipher
	--with-sqlite3lib
	--without-sqlite3lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/extensions/arm64-darwin-21/3.1.0-static/sqlite3-1.4.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.2 for inspection.
Results logged to
/Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/extensions/arm64-darwin-21/3.1.0-static/sqlite3-1.4.2/gem_make.out

  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/3.1.0/rubygems/installer.rb:847:in `build_extensions'
/Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/installer/gem_installer.rb:54:in `install'
/Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/installer/parallel_installer.rb:177:in `block in
worker_pool'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/worker.rb:62:in `apply_func'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/worker.rb:54:in `loop'
  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/worker.rb:54:in `process_queue'
/Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.6/lib/bundler/worker.rb:91:in `block (2 levels) in
create_threads'

An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue.

In Gemfile:
  sqlite3
```

The error log looks like this:
```
❯ cat  /Users/jay/.frum/versions/3.1.0/lib/ruby/gems/3.1.0/extensions/arm64-darwin-21/3.1.0-static/sqlite3-1.4.2/mkmf.log
PKG_CONFIG_PATH = /opt/homebrew/opt/sqlite/lib/pkgconfig
DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib PKG_CONFIG_PATH=/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig pkg-config --exists sqlite3
DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib PKG_CONFIG_PATH=/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig {"PKG_CONFIG_PATH"=>"/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig"} pkg-config --libs sqlite3 |
=> "-L/opt/homebrew/Cellar/sqlite/3.37.2/lib -lsqlite3\n"
DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib "clang -o conftest -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/arm64-darwin21 -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/ruby/backward -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0 -I. -I/opt/homebrew/opt/sqlite/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -pipe conftest.c  -L. -L/Users/jay/.frum/versions/3.1.0/lib -L/opt/homebrew/opt/sqlite/lib -L. -fstack-protector-strong -L/usr/local/lib     -lruby.3.1-static -framework CoreFoundation -lpthread -ldl -lobjc   "
ld: warning: ignoring file /Users/jay/.frum/versions/3.1.0/lib/libruby.3.1-static.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib "clang -o conftest -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/arm64-darwin21 -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/ruby/backward -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0 -I. -I/opt/homebrew/opt/sqlite/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -pipe conftest.c  -L. -L/Users/jay/.frum/versions/3.1.0/lib -L/opt/homebrew/opt/sqlite/lib -L. -fstack-protector-strong -L/usr/local/lib     -lruby.3.1-static -framework CoreFoundation -lpthread -ldl -lobjc -L/opt/homebrew/Cellar/sqlite/3.37.2/lib -lsqlite3  "
ld: warning: ignoring file /Users/jay/.frum/versions/3.1.0/lib/libruby.3.1-static.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/sqlite/lib/libsqlite3.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib PKG_CONFIG_PATH=/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig {"PKG_CONFIG_PATH"=>"/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig"} pkg-config --cflags-only-I sqlite3 |
=> "-I/opt/homebrew/Cellar/sqlite/3.37.2/include\n"
DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib PKG_CONFIG_PATH=/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig {"PKG_CONFIG_PATH"=>"/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig"} pkg-config --cflags-only-other sqlite3 |
=> "\n"
DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib PKG_CONFIG_PATH=/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig {"PKG_CONFIG_PATH"=>"/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig"} pkg-config --libs-only-l sqlite3 |
=> "-lsqlite3\n"
package configuration for sqlite3
incflags: -I/opt/homebrew/Cellar/sqlite/3.37.2/include
cflags:
ldflags: -L/opt/homebrew/Cellar/sqlite/3.37.2/lib
libs: -lsqlite3

find_header: checking for sqlite3.h... -------------------- yes

DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib "clang -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/arm64-darwin21 -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/ruby/backward -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0 -I. -I/opt/homebrew/Cellar/sqlite/3.37.2/include -I/opt/homebrew/opt/sqlite/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -pipe    -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <sqlite3.h>
/* end */

--------------------

find_library: checking for pthread_create() in -lpthread... -------------------- yes

DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib "clang -o conftest -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/arm64-darwin21 -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/ruby/backward -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0 -I. -I/opt/homebrew/Cellar/sqlite/3.37.2/include -I/opt/homebrew/opt/sqlite/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -pipe  conftest.c  -L. -L/Users/jay/.frum/versions/3.1.0/lib -L/opt/homebrew/opt/sqlite/lib -L. -fstack-protector-strong -L/usr/local/lib -L/opt/homebrew/Cellar/sqlite/3.37.2/lib     -lsqlite3 -lruby.3.1-static -framework CoreFoundation -lpthread -ldl -lobjc -lpthread  -lsqlite3  "
conftest.c:14:57: error: use of undeclared identifier 'pthread_create'
int t(void) { void ((*volatile p)()); p = (void ((*)()))pthread_create; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))pthread_create; return !p; }
/* end */

DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib "clang -o conftest -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/arm64-darwin21 -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/ruby/backward -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0 -I. -I/opt/homebrew/Cellar/sqlite/3.37.2/include -I/opt/homebrew/opt/sqlite/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -pipe  conftest.c  -L. -L/Users/jay/.frum/versions/3.1.0/lib -L/opt/homebrew/opt/sqlite/lib -L. -fstack-protector-strong -L/usr/local/lib -L/opt/homebrew/Cellar/sqlite/3.37.2/lib     -lsqlite3 -lruby.3.1-static -framework CoreFoundation -lpthread -ldl -lobjc -lpthread  -lsqlite3  "
ld: warning: ignoring file /opt/homebrew/opt/sqlite/lib/libsqlite3.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/jay/.frum/versions/3.1.0/lib/libruby.3.1-static.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: extern void pthread_create();
15: int t(void) { pthread_create(); return 0; }
/* end */

--------------------

have_library: checking for -ldl... -------------------- yes

DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib "clang -o conftest -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/arm64-darwin21 -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/ruby/backward -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0 -I. -I/opt/homebrew/Cellar/sqlite/3.37.2/include -I/opt/homebrew/opt/sqlite/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -pipe  conftest.c  -L. -L/Users/jay/.frum/versions/3.1.0/lib -L/opt/homebrew/opt/sqlite/lib -L. -fstack-protector-strong -L/usr/local/lib -L/opt/homebrew/Cellar/sqlite/3.37.2/lib    -lpthread  -lsqlite3 -lruby.3.1-static -framework CoreFoundation -lpthread -ldl -lobjc -ldl -lpthread  -lsqlite3  "
ld: warning: ignoring file /opt/homebrew/opt/sqlite/lib/libsqlite3.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/jay/.frum/versions/3.1.0/lib/libruby.3.1-static.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14:
15: int t(void) { ; return 0; }
/* end */

--------------------

find_library: checking for sqlite3_libversion_number() in -lsqlite3... -------------------- no

DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib "clang -o conftest -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/arm64-darwin21 -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/ruby/backward -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0 -I. -I/opt/homebrew/Cellar/sqlite/3.37.2/include -I/opt/homebrew/opt/sqlite/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -pipe  conftest.c  -L. -L/Users/jay/.frum/versions/3.1.0/lib -L/opt/homebrew/opt/sqlite/lib -L. -fstack-protector-strong -L/usr/local/lib -L/opt/homebrew/Cellar/sqlite/3.37.2/lib    -ldl -lpthread  -lsqlite3 -lruby.3.1-static -framework CoreFoundation -lpthread -ldl -lobjc -lsqlite3 -ldl -lpthread  -lsqlite3  "
conftest.c:14:57: error: use of undeclared identifier 'sqlite3_libversion_number'
int t(void) { void ((*volatile p)()); p = (void ((*)()))sqlite3_libversion_number; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))sqlite3_libversion_number; return !p; }
/* end */

DYLD_FALLBACK_LIBRARY_PATH=.:/Users/jay/.frum/versions/3.1.0/lib "clang -o conftest -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/arm64-darwin21 -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0/ruby/backward -I/Users/jay/.frum/versions/3.1.0/include/ruby-3.1.0 -I. -I/opt/homebrew/Cellar/sqlite/3.37.2/include -I/opt/homebrew/opt/sqlite/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -pipe  conftest.c  -L. -L/Users/jay/.frum/versions/3.1.0/lib -L/opt/homebrew/opt/sqlite/lib -L. -fstack-protector-strong -L/usr/local/lib -L/opt/homebrew/Cellar/sqlite/3.37.2/lib    -ldl -lpthread  -lsqlite3 -lruby.3.1-static -framework CoreFoundation -lpthread -ldl -lobjc -lsqlite3 -ldl -lpthread  -lsqlite3  "
ld: warning: ignoring file /opt/homebrew/opt/sqlite/lib/libsqlite3.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/jay/.frum/versions/3.1.0/lib/libruby.3.1-static.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_sqlite3_libversion_number", referenced from:
      _t in conftest-430792.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: extern void sqlite3_libversion_number();
15: int t(void) { sqlite3_libversion_number(); return 0; }
/* end */

--------------------
```

As the warning says, it's `building for macOS-x86_64 but attempting to link with file built for macOS-arm64`. The question is, how do I set up this build process so that it builds for macOS-arm64 and not macOS-x86_64? Thank you very much.

**Comment by richardadrian** [comment]
having same issue

**Comment by jaywritescode** [comment]
I made some progress by adding the following to my `~/.bundle/config`:
```
BUNDLE_BUILD__SQLITE3: "--with-sqlite3-include=/usr/local/opt/sqlite3/include --with-sqlite3-lib=/usr/local/opt/sqlite3/lib"
```
This solution only "works" (i.e., the compilation still fails, just in a different way) if those two paths: `/usr/local/opt/sqlite3/include` and `/usr/local/opt/sqlite3/lib` exist:
```
> /usr/local/opt/sqlite3/bin/sqlite3 --version
3.37.0 2021-11-27 14:13:22 bd41822c7424d393a30e92ff6cb254d25c26769889c1499a18a0b9339f5d6c8a
```

Now the compiler is erroring out on undefined variables:
```
sqlite3.c:35:20: error: implicit declaration of function 'RBIGNUM' is invalid in
C99 [-Werror,-Wimplicit-function-declaration]
  const long len = RBIGNUM_LEN(value);
                   ^
sqlite3.c:33:27: note: expanded from macro 'RBIGNUM_LEN'
#   define RBIGNUM_LEN(x) RBIGNUM(x)->len
                          ^
sqlite3.c:35:20: error: member reference type 'int' is not a pointer
  const long len = RBIGNUM_LEN(value);
                   ^~~~~~~~~~~~~~~~~~
sqlite3.c:33:39: note: expanded from macro 'RBIGNUM_LEN'
#   define RBIGNUM_LEN(x) RBIGNUM(x)->len
                          ~~~~~~~~~~  ^
sqlite3.c:40:19: error: use of undeclared identifier 'SIZEOF_BDIGITS'
  if (len > 63 / (SIZEOF_BDIGITS * CHAR_BIT) + 1) return 0;
                  ^
sqlite3.c:41:20: error: use of undeclared identifier 'SIZEOF_BDIGITS'
  if (len == 63 / (SIZEOF_BDIGITS * CHAR_BIT) + 1) {
                   ^
sqlite3.c:42:11: error: unknown type name 'BDIGIT'
    const BDIGIT *digits = RBIGNUM_DIGITS(value);
          ^
sqlite3.c:42:28: error: implicit declaration of function 'RBIGNUM_DIGITS' is
invalid in C99 [-Werror,-Wimplicit-function-declaration]
    const BDIGIT *digits = RBIGNUM_DIGITS(value);
                           ^
sqlite3.c:43:5: error: use of undeclared identifier 'BDIGIT'
    BDIGIT blast = digits[len-1];
    ^
sqlite3.c:44:5: error: use of undeclared identifier 'BDIGIT'
    BDIGIT bmax = (BDIGIT)1UL << (63 % (CHAR_BIT * SIZEOF_BDIGITS));
    ^
sqlite3.c:45:9: error: use of undeclared identifier 'blast'
    if (blast > bmax) return 0;
        ^
sqlite3.c:45:17: error: use of undeclared identifier 'bmax'
    if (blast > bmax) return 0;
                ^
sqlite3.c:46:9: error: use of undeclared identifier 'blast'
    if (blast == bmax) {
        ^
sqlite3.c:46:18: error: use of undeclared identifier 'bmax'
    if (blast == bmax) {
                 ^
12 errors generated.
make: *** [sqlite3.o] Error 1
```
Does anyone know how to solve this problem?

**Comment by garside** [comment]
Same problem here. Can't get sqlite3 to install on the M1 Mac. Confirmed identical problem as above to @jaywritescode . Brand new out of the box M1 with ZSH and brew installed sqlite. Followed tutorial to get my gems working on a new machine and wound up here. 

Big sadge :(

**Comment by flavorjones** [comment]
Sorry y'all are having problems with this. I'm working on updating sqlite3 with precompiled native packages, and along the way I'll tackle M1 support. Hang tight for a bit!

**Comment by flavorjones** [comment]
#320 has a patch that updates the automake files `config.guess` and `config.sub` to support `arm64-darwin` platforms.

**Comment by SpyMachine** [comment]
Just tried it, worked for me. Cheers!

**Comment by flavorjones** [comment]
v1.5.0 final is out.
