### ISSUE TITLE
Segmentation Fault if `load_extension` with Pathname

### ISSUE THREAD

**Issue by rongcuid** [sparklemotion/sqlite3-ruby#339]
I am trying to load `https://github.com/phiresky/sqlite-zstd`. Ruby Segfaults if I try to use `Pathname` instead of string:

```ruby
require 'sqlite3'
require 'pathname'

puts "sqlite3 gem version: #{SQLite3::VERSION}"
puts "SQLite3 version: #{SQLite3::SQLITE_VERSION}"

db = SQLite3::Database.new(':memory:')
db.enable_load_extension(true)
ext = Pathname.new('./libsqlite_zstd')
db.load_extension(ext) # Crash
# db.load_extension(ext.to_s) # Works
```

Core dump:

```
-> ruby test.rb 
sqlite3 gem version: 1.4.4
SQLite3 version: 3.26.0
test.rb:10: [BUG] Segmentation fault at 0x0000000000000020
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0013 e:000012 CFUNC  :load_extension
c:0002 p:0109 s:0008 E:001e50 EVAL   test.rb:10 [FINISH]
c:0001 p:0000 s:0003 E:000c30 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
test.rb:10:in `<main>'
test.rb:10:in `load_extension'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f72bfbfd007 RBP: 0x0000000000000034 RSP: 0x00007fff9d3eff08
 RAX: 0x0000000000000000 RBX: 0x0000000001e1f868 RCX: 0x0000000000000014
 RDX: 0x0000000000000034 RDI: 0x0000000000000020 RSI: 0x0000000000000000
  R8: 0x0000000001e3f678  R9: 0x00007f72bc267a60 R10: 0x0000000000000012
 R11: 0x00007f72bbb68ac0 R12: 0x00007f72bbe18d80 R13: 0x00007f72c1749f90
 R14: 0x00007f72bc267a60 R15: 0x00007fff9d3eff88 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(rb_print_backtrace+0x11) [0x7f72c122c7fb] vm_dump.c:759
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(rb_vm_bugreport) vm_dump.c:1045
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(rb_bug_for_fatal_signal+0xf0) [0x7f72c104bd00] error.c:821
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(sigsegv+0x4b) [0x7f72c11912fb] signal.c:964
/lib64/libpthread.so.0(__restore_rt+0x0) [0x7f72c0b57cf0]
/lib64/libc.so.6(__strlen_avx2+0x47) [0x7f72bfbfd007]
/lib64/libsqlite3.so.0(sqlite3_load_extension+0x56) [0x7f72bbb68b16]
/home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/sqlite3_native.so(load_extension+0x6e) [0x7f72bbe3283e] database.c:607
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(vm_call_cfunc_with_frame+0xfb) [0x7f72c1211fcb] vm_insnhelper.c:3037
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(vm_call_method_each_type+0xee) [0x7f72c122454e] vm_insnhelper.c:3639
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(vm_call_method+0xb4) [0x7f72c1224e94] vm_insnhelper.c:3750
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(vm_sendish+0x10) [0x7f72c121613d] vm_insnhelper.c:4751
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(vm_exec_core) insns.def:778
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(rb_vm_exec+0x781) [0x7f72c121c1e1] vm.c:2220
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(rb_ec_exec_node+0xab) [0x7f72c105079b] eval.c:280
/u/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1(ruby_run_node+0x55) [0x7f72c1056925] eval.c:321
/home/vax9/u5/rdong3/.rbenv/versions/3.1.2/bin/ruby(main+0x5b) [0x4008eb] ./main.c:47

-- Other runtime information -----------------------------------------------

* Loaded script: test.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 fiber.so
    3 rational.so
    4 complex.so
    5 ruby2_keywords.rb
    6 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/encdb.so
    7 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/trans/transdb.so
    8 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/rbconfig.rb
    9 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/compatibility.rb
   10 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/defaults.rb
   11 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/deprecate.rb
   12 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/errors.rb
   13 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/unknown_command_spell_checker.rb
   14 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/exceptions.rb
   15 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb
   16 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/stub_specification.rb
   17 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/platform.rb
   18 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/version.rb
   19 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/requirement.rb
   20 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/util/list.rb
   21 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb
   22 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/util.rb
   23 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/dependency.rb
   24 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_gem.rb
   25 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/monitor.so
   26 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/monitor.rb
   27 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb
   28 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_warn.rb
   29 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems.rb
   30 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/path_support.rb
   31 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/error_highlight/version.rb
   32 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/error_highlight/base.rb
   33 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/error_highlight/formatter.rb
   34 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/error_highlight/core_ext.rb
   35 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/error_highlight.rb
   36 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/version.rb
   37 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/core_ext/name_error.rb
   38 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/levenshtein.rb
   39 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/jaro_winkler.rb
   40 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checker.rb
   41 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   42 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   43 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checkers/name_error_checkers.rb
   44 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checkers/method_name_checker.rb
   45 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checkers/key_error_checker.rb
   46 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checkers/null_checker.rb
   47 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/tree_spell_checker.rb
   48 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checkers/require_path_checker.rb
   49 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/spell_checkers/pattern_key_name_checker.rb
   50 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean/formatter.rb
   51 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/did_you_mean.rb
   52 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/sqlite3_native.so
   53 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/constants.rb
   54 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/errors.rb
   55 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/pragmas.rb
   56 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/resultset.rb
   57 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/statement.rb
   58 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/date_core.so
   59 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/date.rb
   60 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/time.rb
   61 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/translator.rb
   62 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/value.rb
   63 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/database.rb
   64 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/version.rb
   65 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3.rb
   66 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/pathname.so
   67 /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/pathname.rb

* Process memory map:

00400000-00401000 r-xp 00000000 00:38 2911793                            /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/bin/ruby
00600000-00601000 r--p 00000000 00:38 2911793                            /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/bin/ruby
00601000-00602000 rw-p 00001000 00:38 2911793                            /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/bin/ruby
01ae5000-01f1c000 rw-p 00000000 00:00 0                                  [heap]
7f72b93dd000-7f72b94f7000 r--s 00000000 08:02 6820038                    /usr/lib64/libsqlite3.so.0.8.6
7f72b94f7000-7f72b96f7000 r--s 00000000 08:02 6819865                    /usr/lib64/libc-2.28.so
7f72b96f7000-7f72b971c000 r--s 00000000 08:02 6819879                    /usr/lib64/libpthread-2.28.so
7f72b971c000-7f72ba7a8000 rw-p 00000000 00:00 0 
7f72ba7a8000-7f72bb43f000 r--s 00000000 00:38 2911794                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1.2
7f72bb43f000-7f72bb474000 r--s 00000000 00:38 2911793                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/bin/ruby
7f72bb474000-7f72bb48b000 r-xp 00000000 08:02 6815763                    /usr/lib64/libgcc_s-8-20210514.so.1
7f72bb48b000-7f72bb68a000 ---p 00017000 08:02 6815763                    /usr/lib64/libgcc_s-8-20210514.so.1
7f72bb68a000-7f72bb68b000 r--p 00016000 08:02 6815763                    /usr/lib64/libgcc_s-8-20210514.so.1
7f72bb68b000-7f72bb68c000 rw-p 00017000 08:02 6815763                    /usr/lib64/libgcc_s-8-20210514.so.1
7f72bb69f000-7f72bb6a6000 r-xp 00000000 00:38 2911821                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/pathname.so
7f72bb6a6000-7f72bb8a6000 ---p 00007000 00:38 2911821                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/pathname.so
7f72bb8a6000-7f72bb8a7000 r--p 00007000 00:38 2911821                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/pathname.so
7f72bb8a7000-7f72bb8a8000 rw-p 00008000 00:38 2911821                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/pathname.so
7f72bb8a8000-7f72bb8bc000 rw-p 00000000 00:00 0 
7f72bb8be000-7f72bb8f2000 r-xp 00000000 00:38 2913243                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/date_core.so
7f72bb8f2000-7f72bbaf1000 ---p 00034000 00:38 2913243                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/date_core.so
7f72bbaf1000-7f72bbaf2000 r--p 00033000 00:38 2913243                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/date_core.so
7f72bbaf2000-7f72bbaf3000 rw-p 00034000 00:38 2913243                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/date_core.so
7f72bbaf3000-7f72bbb04000 rw-p 00000000 00:00 0 
7f72bbb06000-7f72bbc14000 r-xp 00000000 08:02 6820038                    /usr/lib64/libsqlite3.so.0.8.6
7f72bbc14000-7f72bbe13000 ---p 0010e000 08:02 6820038                    /usr/lib64/libsqlite3.so.0.8.6
7f72bbe13000-7f72bbe17000 r--p 0010d000 08:02 6820038                    /usr/lib64/libsqlite3.so.0.8.6
7f72bbe17000-7f72bbe1a000 rw-p 00111000 08:02 6820038                    /usr/lib64/libsqlite3.so.0.8.6
7f72bbe20000-7f72bbe2c000 rw-p 00000000 00:00 0 
7f72bbe2d000-7f72bbe37000 r-xp 00000000 00:38 2889971                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/sqlite3_native.so
7f72bbe37000-7f72bc036000 ---p 0000a000 00:38 2889971                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/sqlite3_native.so
7f72bc036000-7f72bc037000 r--p 00009000 00:38 2889971                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/sqlite3_native.so
7f72bc037000-7f72bc038000 rw-p 0000a000 00:38 2889971                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/sqlite3_native.so
7f72bc038000-7f72bc03c000 rw-p 00000000 00:00 0 
7f72bc03d000-7f72bc03f000 r-xp 00000000 00:38 2911820                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/monitor.so
7f72bc03f000-7f72bc23e000 ---p 00002000 00:38 2911820                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/monitor.so
7f72bc23e000-7f72bc23f000 r--p 00001000 00:38 2911820                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/monitor.so
7f72bc23f000-7f72bc240000 rw-p 00002000 00:38 2911820                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/monitor.so
7f72bc240000-7f72bc280000 rw-p 00000000 00:00 0 
7f72bc281000-7f72bc283000 r-xp 00000000 00:38 2913184                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/trans/transdb.so
7f72bc283000-7f72bc483000 ---p 00002000 00:38 2913184                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/trans/transdb.so
7f72bc483000-7f72bc484000 r--p 00002000 00:38 2913184                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/trans/transdb.so
7f72bc484000-7f72bc485000 rw-p 00003000 00:38 2913184                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/trans/transdb.so
7f72bc485000-7f72bc487000 r-xp 00000000 00:38 2911841                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/encdb.so
7f72bc487000-7f72bc686000 ---p 00002000 00:38 2911841                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/encdb.so
7f72bc686000-7f72bc687000 r--p 00001000 00:38 2911841                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/encdb.so
7f72bc687000-7f72bc688000 rw-p 00002000 00:38 2911841                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/ruby/3.1.0/x86_64-linux/enc/encdb.so
7f72bc688000-7f72bc689000 ---p 00000000 00:00 0 
7f72bc689000-7f72bc72a000 rw-p 00000000 00:00 0 
7f72bc72a000-7f72bc72b000 ---p 00000000 00:00 0 
7f72bc72b000-7f72bc7cc000 rw-p 00000000 00:00 0 
7f72bc7cc000-7f72bc7cd000 ---p 00000000 00:00 0 
7f72bc7cd000-7f72bc86e000 rw-p 00000000 00:00 0 
7f72bc86e000-7f72bc86f000 ---p 00000000 00:00 0 
7f72bc86f000-7f72bc910000 rw-p 00000000 00:00 0 
7f72bc910000-7f72bc911000 ---p 00000000 00:00 0 
7f72bc911000-7f72bc9b2000 rw-p 00000000 00:00 0 
7f72bc9b2000-7f72bc9b3000 ---p 00000000 00:00 0 
7f72bc9b3000-7f72bca54000 rw-p 00000000 00:00 0 
7f72bca54000-7f72bca55000 ---p 00000000 00:00 0 
7f72bca55000-7f72bcaf6000 rw-p 00000000 00:00 0 
7f72bcaf6000-7f72bcaf7000 ---p 00000000 00:00 0 
7f72bcaf7000-7f72bcb98000 rw-p 00000000 00:00 0 
7f72bcb98000-7f72bcb99000 ---p 00000000 00:00 0 
7f72bcb99000-7f72bcc3a000 rw-p 00000000 00:00 0 
7f72bcc3a000-7f72bcc3b000 ---p 00000000 00:00 0 
7f72bcc3b000-7f72bccdc000 rw-p 00000000 00:00 0 
7f72bccdc000-7f72bccdd000 ---p 00000000 00:00 0 
7f72bccdd000-7f72bcd7e000 rw-p 00000000 00:00 0 
7f72bcd7e000-7f72bcd7f000 ---p 00000000 00:00 0 
7f72bcd7f000-7f72bce20000 rw-p 00000000 00:00 0 
7f72bce20000-7f72bce21000 ---p 00000000 00:00 0 
7f72bce21000-7f72bcec2000 rw-p 00000000 00:00 0 
7f72bcec2000-7f72bcec3000 ---p 00000000 00:00 0 
7f72bcec3000-7f72bcf64000 rw-p 00000000 00:00 0 
7f72bcf64000-7f72bcf65000 ---p 00000000 00:00 0 
7f72bcf65000-7f72bd006000 rw-p 00000000 00:00 0 
7f72bd006000-7f72bd007000 ---p 00000000 00:00 0 
7f72bd007000-7f72bd0a8000 rw-p 00000000 00:00 0 
7f72bd0a8000-7f72bd0a9000 ---p 00000000 00:00 0 
7f72bd0a9000-7f72bd14a000 rw-p 00000000 00:00 0 
7f72bd14a000-7f72bd14b000 ---p 00000000 00:00 0 
7f72bd14b000-7f72bd1ec000 rw-p 00000000 00:00 0 
7f72bd1ec000-7f72bd1ed000 ---p 00000000 00:00 0 
7f72bd1ed000-7f72bd28e000 rw-p 00000000 00:00 0 
7f72bd28e000-7f72bd28f000 ---p 00000000 00:00 0 
7f72bd28f000-7f72bd330000 rw-p 00000000 00:00 0 
7f72bd330000-7f72bd331000 ---p 00000000 00:00 0 
7f72bd331000-7f72bd3d2000 rw-p 00000000 00:00 0 
7f72bd3d2000-7f72bd3d3000 ---p 00000000 00:00 0 
7f72bd3d3000-7f72bd474000 rw-p 00000000 00:00 0 
7f72bd474000-7f72bd475000 ---p 00000000 00:00 0 
7f72bd475000-7f72bd516000 rw-p 00000000 00:00 0 
7f72bd516000-7f72bd517000 ---p 00000000 00:00 0 
7f72bd517000-7f72bd5b8000 rw-p 00000000 00:00 0 
7f72bd5b8000-7f72bd5b9000 ---p 00000000 00:00 0 
7f72bd5b9000-7f72bd65a000 rw-p 00000000 00:00 0 
7f72bd65a000-7f72bd65b000 ---p 00000000 00:00 0 
7f72bd65b000-7f72bd6fc000 rw-p 00000000 00:00 0 
7f72bd6fc000-7f72bd6fd000 ---p 00000000 00:00 0 
7f72bd6fd000-7f72bd79e000 rw-p 00000000 00:00 0 
7f72bd79e000-7f72bd79f000 ---p 00000000 00:00 0 
7f72bd79f000-7f72bd840000 rw-p 00000000 00:00 0 
7f72bd840000-7f72bd841000 ---p 00000000 00:00 0 
7f72bd841000-7f72bd8e2000 rw-p 00000000 00:00 0 
7f72bd8e2000-7f72bd8e3000 ---p 00000000 00:00 0 
7f72bd8e3000-7f72bd984000 rw-p 00000000 00:00 0 
7f72bd984000-7f72bd985000 ---p 00000000 00:00 0 
7f72bd985000-7f72bda26000 rw-p 00000000 00:00 0 
7f72bda26000-7f72bda27000 ---p 00000000 00:00 0 
7f72bda27000-7f72bfac8000 rw-p 00000000 00:00 0 
7f72bfacf000-7f72bfb30000 rw-p 00000000 00:00 0 
7f72bfb30000-7f72bfcec000 r-xp 00000000 08:02 6819865                    /usr/lib64/libc-2.28.so
7f72bfcec000-7f72bfeec000 ---p 001bc000 08:02 6819865                    /usr/lib64/libc-2.28.so
7f72bfeec000-7f72bfef0000 r--p 001bc000 08:02 6819865                    /usr/lib64/libc-2.28.so
7f72bfef0000-7f72bfef2000 rw-p 001c0000 08:02 6819865                    /usr/lib64/libc-2.28.so
7f72bfef2000-7f72bfef6000 rw-p 00000000 00:00 0 
7f72bfef6000-7f72c0077000 r-xp 00000000 08:02 6819869                    /usr/lib64/libm-2.28.so
7f72c0077000-7f72c0276000 ---p 00181000 08:02 6819869                    /usr/lib64/libm-2.28.so
7f72c0276000-7f72c0277000 r--p 00180000 08:02 6819869                    /usr/lib64/libm-2.28.so
7f72c0277000-7f72c0278000 rw-p 00181000 08:02 6819869                    /usr/lib64/libm-2.28.so
7f72c0278000-7f72c0298000 r-xp 00000000 08:02 6820044                    /usr/lib64/libcrypt.so.1.1.0
7f72c0298000-7f72c0497000 ---p 00020000 08:02 6820044                    /usr/lib64/libcrypt.so.1.1.0
7f72c0497000-7f72c0498000 r--p 0001f000 08:02 6820044                    /usr/lib64/libcrypt.so.1.1.0
7f72c0498000-7f72c04a1000 rw-p 00000000 00:00 0 
7f72c04a1000-7f72c04a4000 r-xp 00000000 08:02 6819867                    /usr/lib64/libdl-2.28.so
7f72c04a4000-7f72c06a3000 ---p 00003000 08:02 6819867                    /usr/lib64/libdl-2.28.so
7f72c06a3000-7f72c06a4000 r--p 00002000 08:02 6819867                    /usr/lib64/libdl-2.28.so
7f72c06a4000-7f72c06a5000 rw-p 00003000 08:02 6819867                    /usr/lib64/libdl-2.28.so
7f72c06a5000-7f72c073b000 r-xp 00000000 08:02 6820024                    /usr/lib64/libgmp.so.10.3.2
7f72c073b000-7f72c093a000 ---p 00096000 08:02 6820024                    /usr/lib64/libgmp.so.10.3.2
7f72c093a000-7f72c093c000 r--p 00095000 08:02 6820024                    /usr/lib64/libgmp.so.10.3.2
7f72c093c000-7f72c093d000 rw-p 00097000 08:02 6820024                    /usr/lib64/libgmp.so.10.3.2
7f72c093d000-7f72c0944000 r-xp 00000000 08:02 6819883                    /usr/lib64/librt-2.28.so
7f72c0944000-7f72c0b43000 ---p 00007000 08:02 6819883                    /usr/lib64/librt-2.28.so
7f72c0b43000-7f72c0b44000 r--p 00006000 08:02 6819883                    /usr/lib64/librt-2.28.so
7f72c0b44000-7f72c0b45000 rw-p 00007000 08:02 6819883                    /usr/lib64/librt-2.28.so
7f72c0b45000-7f72c0b60000 r-xp 00000000 08:02 6819879                    /usr/lib64/libpthread-2.28.so
7f72c0b60000-7f72c0d5f000 ---p 0001b000 08:02 6819879                    /usr/lib64/libpthread-2.28.so
7f72c0d5f000-7f72c0d60000 r--p 0001a000 08:02 6819879                    /usr/lib64/libpthread-2.28.so
7f72c0d60000-7f72c0d61000 rw-p 0001b000 08:02 6819879                    /usr/lib64/libpthread-2.28.so
7f72c0d61000-7f72c0d65000 rw-p 00000000 00:00 0 
7f72c0d65000-7f72c0d7b000 r-xp 00000000 08:02 6820008                    /usr/lib64/libz.so.1.2.11
7f72c0d7b000-7f72c0f7b000 ---p 00016000 08:02 6820008                    /usr/lib64/libz.so.1.2.11
7f72c0f7b000-7f72c0f7c000 r--p 00016000 08:02 6820008                    /usr/lib64/libz.so.1.2.11
7f72c0f7c000-7f72c0f7d000 rw-p 00000000 00:00 0 
7f72c0f7d000-7f72c136e000 r-xp 00000000 00:38 2911794                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1.2
7f72c136e000-7f72c156d000 ---p 003f1000 00:38 2911794                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1.2
7f72c156d000-7f72c1574000 r--p 003f0000 00:38 2911794                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1.2
7f72c1574000-7f72c1578000 rw-p 003f7000 00:38 2911794                    /home/vax9/u5/rdong3/.rbenv/versions/3.1.2/lib/libruby.so.3.1.2
7f72c1578000-7f72c158a000 rw-p 00000000 00:00 0 
7f72c158a000-7f72c15b7000 r-xp 00000000 08:02 6819858                    /usr/lib64/ld-2.28.so
7f72c15bc000-7f72c1648000 rw-p 00000000 00:00 0 
7f72c164a000-7f72c174b000 rw-p 00000000 00:00 0 
7f72c174b000-7f72c179e000 r--p 00000000 08:02 7341149                    /usr/lib/locale/C.utf8/LC_CTYPE
7f72c179e000-7f72c17a2000 rw-p 00000000 00:00 0 
7f72c17a8000-7f72c17ac000 rw-p 00000000 00:00 0 
7f72c17ae000-7f72c17b5000 r--s 00000000 08:02 7341212                    /usr/lib64/gconv/gconv-modules.cache
7f72c17b5000-7f72c17b7000 rw-p 00000000 00:00 0 
7f72c17b7000-7f72c17b8000 r--p 0002d000 08:02 6819858                    /usr/lib64/ld-2.28.so
7f72c17b8000-7f72c17ba000 rw-p 0002e000 08:02 6819858                    /usr/lib64/ld-2.28.so
7fff9cbf5000-7fff9d3f4000 rw-p 00000000 00:00 0                          [stack]
7fff9d3f8000-7fff9d3fc000 r--p 00000000 00:00 0                          [vvar]
7fff9d3fc000-7fff9d3fe000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


Aborted (core dumped)
```

**Comment by flavorjones** [comment]
Thanks for reporting this! #340 is a PR that will raise a TypeError in this situation.
