### ISSUE TITLE
SQLite3::Database#execute_batch fails with non-ASCII characters

### ISSUE THREAD

**Issue by Math2** [sparklemotion/sqlite3-ruby#524]
Before v2.0.0, the following used to work:

```ruby
require 'sqlite3'

db = SQLite3::Database.new ':memory:'

db.execute_batch %{
  CREATE TABLE test(t TEXT);
  INSERT INTO test VALUES ('héhé');
}
```

But now fails with:

```
/usr/home/mathieu/.gem/ruby/3.2/gems/sqlite3-2.0.0/lib/sqlite3/statement.rb:31:in `encode': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
        from /usr/home/mathieu/.gem/ruby/3.2/gems/sqlite3-2.0.0/lib/sqlite3/statement.rb:31:in `initialize'
        from /usr/home/mathieu/.gem/ruby/3.2/gems/sqlite3-2.0.0/lib/sqlite3/database.rb:166:in `new'
        from /usr/home/mathieu/.gem/ruby/3.2/gems/sqlite3-2.0.0/lib/sqlite3/database.rb:166:in `prepare'
        from /usr/home/mathieu/.gem/ruby/3.2/gems/sqlite3-2.0.0/lib/sqlite3/database.rb:250:in `execute_batch'
        from ./test.rb:5:in `<main>'

```

**Comment by flavorjones** [comment]
@Math2 Thanks for reporting this. I'll take a look!

**Comment by flavorjones** [comment]
Bisecting indicates a9a89f89971aa784730d566f53c1820ca9185bf4 is the commit that introduced this behavior. It looks like the "tail" string comes back from `#prepare` as `ASCII-8BIT` because we're doing the encoding slightly differently.

I've got a fix, just writing up some tests and I'll create the PR shortly.

**Comment by flavorjones** [comment]
See #526 for the proposed fix.

**Comment by flavorjones** [comment]
Fix released in https://github.com/sparklemotion/sqlite3-ruby/releases/tag/v2.0.1
