### ISSUE TITLE
Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1. Make sure all dependencies are added to Gemfile. (LoadError)

### ISSUE THREAD

**Issue by lucascaton** [sparklemotion/sqlite3-ruby#529]
Hi there 👋

I'm [updating a gem to support SQLite3 v2](https://github.com/lucascaton/enumerate_it/pull/110) but whenever I use version 2.x, I get the following error:

`Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-arm64-darwin. Make sure all dependencies are added to Gemfile. (LoadError)`

## How to reproduce it:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", ">= 7.1"
  # gem "sqlite3", "< 2"
  gem "sqlite3", ">= 2"
end

require "active_record"
# require "sqlite3" # This doesn't seem to make a difference

puts "SQLite3::VERSION: #{SQLite3::VERSION}"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
```

## Results:

With `gem "sqlite3", "< 2"`:

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
SQLite3::VERSION: 1.7.3
✅
```

With `gem "sqlite3", ">= 2"`:

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
SQLite3::VERSION: 2.0.1
❌
~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/rubygems_integration.rb:237:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-arm64-darwin. Make sure all dependencies are added to Gemfile. (LoadError)
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:333:in `resolve_pool_config'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:134:in `establish_connection'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:53:in `establish_connection'
	from replication.rb:18:in `<main>'
~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/rubygems_integration.rb:237:in `block (2 levels) in replace_gem': can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-arm64-darwin. Make sure all dependencies are added to Gemfile. (Gem::LoadError)
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:333:in `resolve_pool_config'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:134:in `establish_connection'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:53:in `establish_connection'
	from replication.rb:18:in `<main>'
```

Sorry if I missed something obvious and thanks in advance 🙂

**Comment by bamnet** [comment]
+1.  Dependabot sent upgrades to my rails app to bump to 2.0.0 but my CI/CD is unhappy.

I think this is because ActiveRecord is still pinned to <2, and we need https://github.com/rails/rails/commit/fd1c635d2f1fd8f348ef9fe8a41fb042a8e43482 to land for it to happyily use 2.x.x  I could be totally wrong though.

**Comment by flavorjones** [comment]
ActiveRecord in Rails 7.1 is pinned to an earlier version of sqlite3. This has been addressed in https://github.com/rails/rails/pull/51592 but you'll need to talk to Rails maintainers to understand what release that will appear in.

**Comment by flavorjones** [comment]
I've proposed a backport to 7-1-stable in https://github.com/rails/rails/pull/51636

**Comment by Fryguy** [comment]
@flavorjones I'm seeing this same issue on older versions of Rails going back to at least Rails 6.0  Can we also get your fix backported to older Rails' that are still supported?

**Comment by flavorjones** [comment]
@Fryguy Feel free to submit a PR upstream!
